#spring.application.name=cadastroDeUsuarios

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/controleDeUsuarios?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
