services:
  db:
      image: mysql
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - leonardo_data:/var/lib/mysql

volumes:
  leonardo_data: